### ISSUE TITLE
3.4 not working with jQuery 2.2.0

### ISSUE THREAD

**Issue by igoramadas** [knockout/knockout#1972]
The "click" binding doesn't work, throws an error saying .on(element).trigger is not a function.

**Comment by brianmhunt** [comment]
@igoramadas It is not clear what might be going on here. Could you perhaps provide a jsFiddle?

**Comment by igoramadas** [comment]
I'm still investigating and will update this issue as soon as I come to the root cause (and don't have a working jsFiddle, working on this right now and will add the link later on). But as a starter:

    input(type="text", title="The team ID can't be changed once it's set!", data-bind="value: id, attr: {readonly: !$parent.teamIdChangeEnabled() && id() != '' && team_id() != '0' && !id.isUpdated()}, click: $parent.confirmChangeId", required)

Error happens when clicking the input field (doesn't even hit the "confirmChangeId" method).

PS: I only get the exception when I use jQuery 2.2.0. Going back to 2.1.4 solves the issue.

**Comment by mbest** [comment]
Please provide an update if this is still a problem. Otherwise we'll close the issue.
